### ISSUE TITLE
Connection Failure errors on MU6500 with firmware version 1250

### ISSUE THREAD

**Issue by TheQueasle** [kdschlosser/samsungctl#5]
Using the latest master branch, I've ~not been able to successfully~ ran into some issues when attempting to control my Samsung TV.

Using the following options
```
python -m samsungctl --host MY_TV_IP --port 8002 --method websocket KEY_MUTE
```
```
error from callback <bound method RemoteWebsocket.on_open of <samsungctl.remote_websocket.RemoteWebsocket object at 0x7f7b877b0b38>>: on_open() missing 1 required positional argument: 'ws'
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/quinnm/Git/github/samsungctl/samsungctl/__main__.py", line 206, in <module>
    main()
  File "/home/quinnm/Git/github/samsungctl/samsungctl/__main__.py", line 181, in main
    with Remote(config) as remote:
  File "/home/quinnm/Git/github/samsungctl/samsungctl/remote.py", line 13, in __init__
    self.remote = RemoteWebsocket(config)
  File "/home/quinnm/Git/github/samsungctl/samsungctl/remote_websocket.py", line 50, in __init__
    self.open()
  File "/home/quinnm/Git/github/samsungctl/samsungctl/remote_websocket.py", line 127, in open
    raise RuntimeError('Connection Failure')
RuntimeError: Connection Failure
```
I get the pop up on my TV asking to allow the connection.  After clicking allow, the output from python updates to
```
error from callback <bound method RemoteWebsocket.on_message of <samsungctl.remote_websocket.RemoteWebsocket object at 0x7f7b877b0b38>>: on_message() missing 1 required positional argument: 'message'
```
and hangs until I <ctrl>+c.

The file `~/.samsungctl/token.txt` does get created, but it is empty.

I did some poking around and found a bug report on websocket-client's project page (https://github.com/websocket-client/websocket-client/issues/471) that had a similar error "missing 1 required positional argument".

The websocket-client issue 471 is marked as closed and fixed in version 0.53.0 of websocket-client, but I was using 0.54.0 when I got the error message(s).

So - long story longer - I started dropping the version of websocket-client until something changed.

I got down to version 0.50.0 and was able to connect, call KEY_MUTE, and the file `~/.samsungctl/token.txt` was populated, though not without some error output.
```
'>' not supported between instances of 'float' and 'NoneType'
```

All that said - thanks for all the work being put into this project and I'm ready to help out any way I can.

**Comment by TheQueasle** [comment]
Quick update:  Dropping down to websocket-client version 0.48.0 and I've yet to hit any error output when controlling my TV.

**Comment by kdschlosser** [comment]
ok I am going to set the version to 48.0 this way the problem goes away. but I will need to see that entire last traceback. Because ultimately this needs to get fixed by the author of the websocket client

I need to know what line and in what file the traceback occured.

and as far as this error
on_message() missing 1 required positional argument: 'message'

what version of the websocket client was being used when this occurs because the author of the websocket-client stated that this error had been fixed. I would have to go and check the version that is on pypi against the version he has on his repo.

**Comment by kdschlosser** [comment]
Never mind. I see what is happening.. you had a version of the websocket client that was already installed and that version had this issue in it. I need to add >= 0.54.0 to the requirements. this is happening because I am using a different connection mechanism in the websocket-client then what was used in the original samsungctl.

You can double check this and uninstall websocket client

    pip install --uninstall websocket-client

 and then run

    pip install --no-cache-dir websocket-client

this will ensure that 0.54.0 gets installed

**Comment by kdschlosser** [comment]
ok I have fixed this issue
