### ISSUE TITLE
Slow response (10+ seconds per command).

### ISSUE THREAD

**Issue by twf75** [kdschlosser/samsungctl#90]
After fiddling with the config file, I have samsungctl working for my Q7 tv. Works a charm, but it's slow as molasses. Each command takes 10 to 20 seconds to process. After some troubleshooting, the culprit seems to be the UPNP scan. If i'm reading the code correctly (and chances are I'm not), the code to scan the UPNP URI's triggers each time the command is started. 

If my research is correct, the "upnp_locations" parameter in the config file should prevent the UPNP discovery from running. However, as the config file generated is not JSON valid, checking this is hard :) 

My config now has:

"upnp_locations": "[uri1], [uri2], [uri3]" (where the uri's are actual working links)

I have NO idea if this format is right, but it appears that this bit of the config is ignored, triggering the rescan, and slow start. 

Question: Is this the correct formatting for this config parameter?

(and seperately: It may be prudent to add 'how to get the token' -> "use --config-file and find it there" to the manual)

**Comment by kdschlosser** [comment]
I have just fixed this issue. the initial scan should take a long time. that is why it is important to save to the config file. the upnp locations get saved to the config file so the scan will not have to take place a second time. it will use the locations entered in the file.

you can give it a try. I would repair the TV and create a new config file. since you have altered how the config file. I do not know how you have the upnp_locations formatted in there. or you can change the upnp_locations to None. that will also do the trick.

I did make the change in a way that will correct any existing config files that have not been altered.

**Comment by twf75** [comment]
After update:
-Deleted old config file
-Made new config file with "samsungctl --host 192.168.1.16 --method websocket --name Domoticz --port 8002 --id 1010 --token 16366725 KEY_MUTE --config-file ~/.config/samsungctl.conf"
-New config file created after about 15 seconds. 
-Running 'samsungctl KEY_MUTE' gives: "Could not parse the configuration file. No JSON object could be decoded" (truncated for brevity, full output available)
-After JSON-ifying the config file: MUCH QUICKER!

From 20 seconds to 3 on the outside. This is great!

Still unsure why it balks at the 'human readable' config, but after some tinkering this works amazingly well. Thanks for the quick update!

(any files or outputs that may help, I'm happy to provide)

**Comment by kdschlosser** [comment]
you need to READ THE DIRECTIONS!!!!

not a valid command line for loading the config file. This mechanism is depreciated It is stated in the documentation.

    samsungctl KEY_MUTE



This is a valid command line for reading the new config files. 

    samsungctl --config-file ~/.config/samsungctl.conf KEY_MUTE

the documentation for --config-file states

```
If this is the first time you are using this library on a TV you must specify --host and key code for the command you wish to execute along with this parameter.

samsungctl --host 192.168.1.100 --config-file "/PATH/FILE.NAME" KEY_MENU

By doing this is will make all of the necessary config file settings that are needed to be made for your TV. After the library has sent the command to your TV it will then save the file. Any calls there after will only need to have --config-file PATH/FILENAME along with the command you wish to perform for a command line options.

samsungctl --config-file "/PATH/FILE.NAME" KEY_MENU
```

I do not think that I could make it easier to understand.

**Comment by twf75** [comment]
Yeah, this is a me-parsing-the-docs issue. The *** depreciated looks, to me, like a comment. I've spent minutes finding the matching reference for those 3 stars... Just me being dense I guess. 

For clarity, for dunces like me: *** Deprecated : The automatic reading of the config files no longer works. Always use --config-file!

Anyway, case closed, I'm a happy camper, and again thanks for the quick fix!

**Comment by kdschlosser** [comment]
no it does still work.

if you use the samsungctl.conf example file and manually enter the information the same way it had to be done with the original samsungctl library.

I have not broken any API from the old samsungctl.

the --config-file is new. it is not apart of that old system..
so there for they will not intermix with each other.

so you either stick with the old way. and manually enter the information into the config file and save it in whatever path it needs to be saved in.. NOTE: this does not support the use of the tokens. tokens are a new thing so the old mechanism does not know how to deal with them

or you can use the mechanism that will make the file for you and will handle the token. and powering on the TV. and a whole bunch of extras.

I wanted to leave things as they were so this updated fork could be used as a drop in replacement for the original samsungctl... and it would remain functioning.. and modifications to the user setup could be made over time. adding more functionality when they wanted to.. I am not a HUGE fan of breaking peoples HA setup. I am trying to also make changes in a manner that would be of minimal impact in order to add them to the users setup easily.

**Comment by kdschlosser** [comment]
hmmm... OK.. i get what you are saying about the \*\*\*  before the depreciated...
need to come up with a better marker for it..
maybe add a line of stars above and below it.

**Comment by kdschlosser** [comment]
ok i updated the documentation.

**Comment by kdschlosser** [comment]
now the question is.. is the speed better??

**Comment by kdschlosser** [comment]
I need to remove the print statement for that It was a debugging this I forgot to remove it.

**Comment by kdschlosser** [comment]
all set sir.,. it has been removed.

**Comment by twf75** [comment]
My hero :)
